    -- Calculate hash values and determine insert/update operations
    -- In Fabric, we use MERGE statement for efficient upsert operations
    MERGE INTO Semantic.ClaimTransactionMeasures AS target
    USING (
        SELECT 
            ctm.*,
            CONVERT(NVARCHAR(128), HASHBYTES('SHA2_512', 
                CONCAT(
                    ctm.FactClaimTransactionLineWCKey, '~',
                    ctm.RevisionNumber, '~',
                    ctm.PolicyWCKey, '~',
                    ctm.PolicyRiskStateWCKey, '~',
                    ctm.ClaimWCKey, '~',
                    ctm.ClaimTransactionLineCategoryKey, '~',
                    ctm.ClaimTransactionWCKey, '~',
                    ctm.ClaimCheckKey, '~',
                    ctm.AgencyKey, '~',
                    CAST(ctm.SourceClaimTransactionCreateDate AS NVARCHAR), '~',
                    ctm.SourceClaimTransactionCreateDateKey, '~',
                    CAST(ctm.TransactionCreateDate AS NVARCHAR), '~',
                    CAST(ctm.TransactionSubmitDate AS NVARCHAR), '~',
                    ctm.NetPaidIndemnity, '~',
                    ctm.NetPaidMedical, '~',
                    ctm.NetPaidExpense, '~',
                    ctm.NetPaidEmployerLiability, '~',
                    ctm.NetPaidLegal, '~',
                    ctm.NetPaidLoss, '~',
                    ctm.NetPaidLossAndExpense, '~',
                    ctm.NetIncurredIndemnity, '~',
                    ctm.NetIncurredMedical, '~',
                    ctm.NetIncurredExpense, '~',
                    ctm.NetIncurredEmployerLiability, '~',
                    ctm.NetIncurredLegal, '~',
                    ctm.NetIncurredLoss, '~',
                    ctm.NetIncurredLossAndExpense, '~',
                    ctm.ReservesIndemnity, '~',
                    ctm.ReservesMedical, '~',
                    ctm.ReservesExpense, '~',
                    ctm.ReservesEmployerLiability, '~',
                    ctm.ReservesLegal, '~',
                    ctm.ReservesLoss, '~',
                    ctm.ReservesLossAndExpense, '~',
                    ctm.GrossPaidIndemnity, '~',
                    ctm.GrossPaidMedical, '~',
                    ctm.GrossPaidExpense, '~',
                    ctm.GrossPaidEmployerLiability, '~',
                    ctm.GrossPaidLegal, '~',
                    ctm.GrossPaidLoss, '~',
                    ctm.GrossPaidLossAndExpense, '~',
                    ctm.GrossIncurredIndemnity, '~',
                    ctm.GrossIncurredMedical, '~',
                    ctm.GrossIncurredExpense, '~',
                    ctm.GrossIncurredEmployerLiability, '~',
                    ctm.GrossIncurredLegal, '~',
                    ctm.GrossIncurredLoss, '~',
                    ctm.GrossIncurredLossAndExpense, '~',
                    ctm.RecoveryIndemnity, '~',
                    ctm.RecoveryMedical, '~',
                    ctm.RecoveryExpense, '~',
                    ctm.RecoveryEmployerLiability, '~',
                    ctm.RecoveryLegal, '~',
                    ctm.RecoveryDeductible, '~',
                    ctm.RecoveryOverpayment, '~',
                    ctm.RecoverySubrogation, '~',
                    ctm.RecoveryApportionmentContribution, '~',
                    ctm.RecoverySecondInjuryFund, '~',
                    ctm.RecoveryLoss, '~',
                    ctm.RecoveryLossAndExpense, '~',
                    ctm.RecoveryNonSubroNonSecondInjuryFundEmployerLiability, '~',
                    ctm.RecoveryNonSubroNonSecondInjuryFundExpense, '~',
                    ctm.RecoveryNonSubroNonSecondInjuryFundIndemnity, '~',
                    ctm.RecoveryNonSubroNonSecondInjuryFundLegal, '~',
                    ctm.RecoveryNonSubroNonSecondInjuryFundMedical, '~',
                    ctm.SourceSystem, '~',
                    ctm.SourceSystemIdentifier, '~',
                    ctm.TransactionAmount, '~',
                    ctm.RecoveryDeductibleEmployerLiability, '~',
                    ctm.RecoveryDeductibleExpense, '~',
                    ctm.RecoveryDeductibleIndemnity, '~',
                    ctm.RecoveryDeductibleMedical, '~',
                    ctm.RecoveryDeductibleLegal, '~',
                    ctm.RetiredInd
                )
            )) AS HashValue,
            CURRENT_TIMESTAMP AS LoadUpdateDate,
            COALESCE(
                (SELECT ps.LoadCreateDate 
                 FROM ProdSource ps 
                 WHERE ps.FactClaimTransactionLineWCKey = ctm.FactClaimTransactionLineWCKey 
                   AND ps.RevisionNumber = ctm.RevisionNumber),
                CURRENT_TIMESTAMP
            ) AS LoadCreateDate,
            CASE 
                WHEN NOT EXISTS (
                    SELECT 1 
                    FROM ProdSource ps 
                    WHERE ps.FactClaimTransactionLineWCKey = ctm.FactClaimTransactionLineWCKey 
                      AND ps.RevisionNumber = ctm.RevisionNumber
                ) THEN 'Inserted'
                WHEN EXISTS (
                    SELECT 1 
                    FROM ProdSource ps 
                    WHERE ps.FactClaimTransactionLineWCKey = ctm.FactClaimTransactionLineWCKey 
                      AND ps.RevisionNumber = ctm.RevisionNumber
                      AND ps.HashValue <> CONVERT(NVARCHAR(128), HASHBYTES('SHA2_512', 
                            CONCAT(
                                ctm.FactClaimTransactionLineWCKey, '~',
                                -- Repeat the same hash calculation as above
                                ctm.RetiredInd
                            )
                        ))
                ) THEN 'Updated'
                ELSE NULL
            END AS AuditOperations
        FROM ClaimTransactionMeasuresData ctm
    ) AS source
    ON (target.FactClaimTransactionLineWCKey = source.FactClaimTransactionLineWCKey 
        AND target.RevisionNumber = source.RevisionNumber)
    WHEN MATCHED AND target.HashValue <> source.HashValue THEN
        UPDATE SET 
            target.PolicyWCKey = source.PolicyWCKey,
            target.PolicyRiskStateWCKey = source.PolicyRiskStateWCKey,
            target.ClaimWCKey = source.ClaimWCKey,
            target.ClaimTransactionLineCategoryKey = source.ClaimTransactionLineCategoryKey,
            target.ClaimTransactionWCKey = source.ClaimTransactionWCKey,
            target.ClaimCheckKey = source.ClaimCheckKey,
            target.AgencyKey = source.AgencyKey,
            target.SourceClaimTransactionCreateDate = source.SourceClaimTransactionCreateDate,
            target.SourceClaimTransactionCreateDateKey = source.SourceClaimTransactionCreateDateKey,
            target.TransactionCreateDate = source.TransactionCreateDate,
            target.TransactionSubmitDate = source.TransactionSubmitDate,
            target.SourceSystem = source.SourceSystem,
            target.RecordEffectiveDate = source.RecordEffectiveDate,
            target.SourceSystemIdentifier = source.SourceSystemIdentifier,
            target.NetPaidIndemnity = source.NetPaidIndemnity,
            target.NetPaidMedical = source.NetPaidMedical,
            target.NetPaidExpense = source.NetPaidExpense,
            target.NetPaidEmployerLiability = source.NetPaidEmployerLiability,
            target.NetPaidLegal = source.NetPaidLegal,
            target.NetPaidLoss = source.NetPaidLoss,
            target.NetPaidLossAndExpense = source.NetPaidLossAndExpense,
            target.NetIncurredIndemnity = source.NetIncurredIndemnity,
            target.NetIncurredMedical = source.NetIncurredMedical,
            target.NetIncurredExpense = source.NetIncurredExpense,
            target.NetIncurredEmployerLiability = source.NetIncurredEmployerLiability,
            target.NetIncurredLegal = source.NetIncurredLegal,
            target.NetIncurredLoss = source.NetIncurredLoss,
            target.NetIncurredLossAndExpense = source.NetIncurredLossAndExpense,
            target.ReservesIndemnity = source.ReservesIndemnity,
            target.ReservesMedical = source.ReservesMedical,
            target.ReservesExpense = source.ReservesExpense,
            target.ReservesEmployerLiability = source.ReservesEmployerLiability,
            target.ReservesLegal = source.ReservesLegal,
            target.ReservesLoss = source.ReservesLoss,
            target.ReservesLossAndExpense = source.ReservesLossAndExpense,
            target.GrossPaidIndemnity = source.GrossPaidIndemnity,
            target.GrossPaidMedical = source.GrossPaidMedical,
            target.GrossPaidExpense = source.GrossPaidExpense,
            target.GrossPaidEmployerLiability = source.GrossPaidEmployerLiability,
            target.GrossPaidLegal = source.GrossPaidLegal,
            target.GrossPaidLoss = source.GrossPaidLoss,
            target.GrossPaidLossAndExpense = source.GrossPaidLossAndExpense,
            target.GrossIncurredIndemnity = source.GrossIncurredIndemnity,
            target.GrossIncurredMedical = source.GrossIncurredMedical,
            target.GrossIncurredExpense = source.GrossIncurredExpense,
            target.GrossIncurredEmployerLiability = source.GrossIncurredEmployerLiability,
            target.GrossIncurredLegal = source.GrossIncurredLegal,
            target.GrossIncurredLoss = source.GrossIncurredLoss,
            target.GrossIncurredLossAndExpense = source.GrossIncurredLossAndExpense,
            target.RecoveryIndemnity = source.RecoveryIndemnity,
            target.RecoveryMedical = source.RecoveryMedical,
            target.RecoveryExpense = source.RecoveryExpense,
            target.RecoveryEmployerLiability = source.RecoveryEmployerLiability,
            target.RecoveryLegal = source.RecoveryLegal,
            target.RecoveryDeductible = source.RecoveryDeductible,
            target.RecoveryOverpayment = source.RecoveryOverpayment,
            target.RecoverySubrogation = source.RecoverySubrogation,
            target.RecoveryApportionmentContribution = source.RecoveryApportionmentContribution,
            target.RecoverySecondInjuryFund = source.RecoverySecondInjuryFund,
            target.RecoveryLoss = source.RecoveryLoss,
            target.RecoveryLossAndExpense = source.RecoveryLossAndExpense,
            target.RecoveryNonSubroNonSecondInjuryFundEmployerLiability = source.RecoveryNonSubroNonSecondInjuryFundEmployerLiability,
            target.RecoveryNonSubroNonSecondInjuryFundExpense = source.RecoveryNonSubroNonSecondInjuryFundExpense,
            target.RecoveryNonSubroNonSecondInjuryFundIndemnity = source.RecoveryNonSubroNonSecondInjuryFundIndemnity,
            target.RecoveryNonSubroNonSecondInjuryFundLegal = source.RecoveryNonSubroNonSecondInjuryFundLegal,
            target.RecoveryNonSubroNonSecondInjuryFundMedical = source.RecoveryNonSubroNonSecondInjuryFundMedical,
            target.TransactionAmount = source.TransactionAmount,
            target.RecoveryDeductibleEmployerLiability = source.RecoveryDeductibleEmployerLiability,
            target.RecoveryDeductibleExpense = source.RecoveryDeductibleExpense,
            target.RecoveryDeductibleIndemnity = source.RecoveryDeductibleIndemnity,
            target.RecoveryDeductibleMedical = source.RecoveryDeductibleMedical,
            target.RecoveryDeductibleLegal = source.RecoveryDeductibleLegal,
            target.RetiredInd = source.RetiredInd,
            target.HashValue = source.HashValue,
            target.LoadUpdateDate = source.LoadUpdateDate,
            target.AuditOperations = source.AuditOperations
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            FactClaimTransactionLineWCKey, RevisionNumber, PolicyWCKey, PolicyRiskStateWCKey,
            ClaimWCKey, ClaimTransactionLineCategoryKey, ClaimTransactionWCKey, ClaimCheckKey,
            AgencyKey, SourceClaimTransactionCreateDate, SourceClaimTransactionCreateDateKey,
            TransactionCreateDate, TransactionSubmitDate, SourceSystem, RecordEffectiveDate,
            SourceSystemIdentifier, NetPaidIndemnity, NetPaidMedical, NetPaidExpense,
            NetPaidEmployerLiability, NetPaidLegal, NetPaidLoss, NetPaidLossAndExpense,
            NetIncurredIndemnity, NetIncurredMedical, NetIncurredExpense, NetIncurredEmployerLiability,
            NetIncurredLegal, NetIncurredLoss, NetIncurredLossAndExpense, ReservesIndemnity,
            ReservesMedical, ReservesExpense, ReservesEmployerLiability, ReservesLegal,
            ReservesLoss, ReservesLossAndExpense, GrossPaidIndemnity, GrossPaidMedical,
            GrossPaidExpense, GrossPaidEmployerLiability, GrossPaidLegal, GrossPaidLoss,
            GrossPaidLossAndExpense, GrossIncurredIndemnity, GrossIncurredMedical,
            GrossIncurredExpense, GrossIncurredEmployerLiability, GrossIncurredLegal,
            GrossIncurredLoss, GrossIncurredLossAndExpense, RecoveryIndemnity, RecoveryMedical,
            RecoveryExpense, RecoveryEmployerLiability, RecoveryLegal, RecoveryDeductible,
            RecoveryOverpayment, RecoverySubrogation, RecoveryApportionmentContribution,
            RecoverySecondInjuryFund, RecoveryLoss, RecoveryLossAndExpense,
            RecoveryNonSubroNonSecondInjuryFundEmployerLiability, RecoveryNonSubroNonSecondInjuryFundExpense,
            RecoveryNonSubroNonSecondInjuryFundIndemnity, RecoveryNonSubroNonSecondInjuryFundLegal,
            RecoveryNonSubroNonSecondInjuryFundMedical, TransactionAmount,
            RecoveryDeductibleEmployerLiability, RecoveryDeductibleExpense, RecoveryDeductibleIndemnity,
            RecoveryDeductibleMedical, RecoveryDeductibleLegal, RetiredInd, HashValue,
            LoadUpdateDate, LoadCreateDate, AuditOperations
        )
        VALUES (
            source.FactClaimTransactionLineWCKey, source.RevisionNumber, source.PolicyWCKey, source.PolicyRiskStateWCKey,
            source.ClaimWCKey, source.ClaimTransactionLineCategoryKey, source.ClaimTransactionWCKey, source.ClaimCheckKey,
            source.AgencyKey, source.SourceClaimTransactionCreateDate, source.SourceClaimTransactionCreateDateKey,
            source.TransactionCreateDate, source.TransactionSubmitDate, source.SourceSystem, source.RecordEffectiveDate,
            source.SourceSystemIdentifier, source.NetPaidIndemnity, source.NetPaidMedical, source.NetPaidExpense,
            source.NetPaidEmployerLiability, source.NetPaidLegal, source.NetPaidLoss, source.NetPaidLossAndExpense,
            source.NetIncurredIndemnity, source.NetIncurredMedical, source.NetIncurredExpense, source.NetIncurredEmployerLiability,
            source.NetIncurredLegal, source.NetIncurredLoss, source.NetIncurredLossAndExpense, source.ReservesIndemnity,
            source.ReservesMedical, source.ReservesExpense, source.ReservesEmployerLiability, source.ReservesLegal,
            source.ReservesLoss, source.ReservesLossAndExpense, source.GrossPaidIndemnity, source.GrossPaidMedical,
            source.GrossPaidExpense, source.GrossPaidEmployerLiability, source.GrossPaidLegal, source.GrossPaidLoss,
            source.GrossPaidLossAndExpense, source.GrossIncurredIndemnity, source.GrossIncurredMedical,
            source.GrossIncurredExpense, source.GrossIncurredEmployerLiability, source.GrossIncurredLegal,
            source.GrossIncurredLoss, source.GrossIncurredLossAndExpense, source.RecoveryIndemnity, source.RecoveryMedical,
            source.RecoveryExpense, source.RecoveryEmployerLiability, source.RecoveryLegal, source.RecoveryDeductible,
            source.RecoveryOverpayment, source.RecoverySubrogation, source.RecoveryApportionmentContribution,
            source.RecoverySecondInjuryFund, source.RecoveryLoss, source.RecoveryLossAndExpense,
            source.RecoveryNonSubroNonSecondInjuryFundEmployerLiability, source.RecoveryNonSubroNonSecondInjuryFundExpense,
            source.RecoveryNonSubroNonSecondInjuryFundIndemnity, source.RecoveryNonSubroNonSecondInjuryFundLegal,
            source.RecoveryNonSubroNonSecondInjuryFundMedical, source.TransactionAmount,
            source.RecoveryDeductibleEmployerLiability, source.RecoveryDeductibleExpense, source.RecoveryDeductibleIndemnity,
            source.RecoveryDeductibleMedical, source.RecoveryDeductibleLegal, source.RetiredInd, source.HashValue,
            source.LoadUpdateDate, source.LoadCreateDate, source.AuditOperations
        );

    -- Return the results
    SELECT 
        FactClaimTransactionLineWCKey,
        RevisionNumber,
        PolicyWCKey,
        PolicyRiskStateWCKey,
        ClaimWCKey,
        ClaimTransactionLineCategoryKey,
        ClaimTransactionWCKey,
        ClaimCheckKey,
        AgencyKey,
        SourceClaimTransactionCreateDate,
        SourceClaimTransactionCreateDateKey,
        TransactionCreateDate,
        TransactionSubmitDate,
        SourceSystem,
        RecordEffectiveDate,
        SourceSystemIdentifier,
        GrossIncurredEmployerLiability,
        GrossIncurredExpense,
        GrossIncurredIndemnity,
        GrossIncurredLegal,
        GrossIncurredLoss,
        GrossIncurredLossAndExpense,
        GrossIncurredMedical,
        GrossPaidEmployerLiability,
        GrossPaidExpense,
        GrossPaidIndemnity,
        GrossPaidLegal,
        GrossPaidLoss,
        GrossPaidLossAndExpense,
        GrossPaidMedical,
        NetIncurredEmployerLiability,
        NetIncurredExpense,
        NetIncurredIndemnity,
        NetIncurredLegal,
        NetIncurredLoss,
        NetIncurredLossAndExpense,
        NetIncurredMedical,
        NetPaidEmployerLiability,
        NetPaidExpense,
        NetPaidIndemnity,
        NetPaidLegal,
        NetPaidLoss,
        NetPaidLossAndExpense,
        NetPaidMedical,
        RecoveryApportionmentContribution,
        RecoveryDeductible,
        RecoveryEmployerLiability,
        RecoveryExpense,
        RecoveryIndemnity,
        RecoveryLegal,
        RecoveryLoss,
        RecoveryLossAndExpense,
        RecoveryMedical,
        RecoveryOverpayment,
        RecoverySecondInjuryFund,
        RecoverySubrogation,
        ReservesEmployerLiability,
        ReservesExpense,
        ReservesIndemnity,
        ReservesLegal,
        ReservesLoss,
        ReservesLossAndExpense,
        ReservesMedical,
        RecoveryNonSubroNonSecondInjuryFundEmployerLiability,
        RecoveryNonSubroNonSecondInjuryFundExpense,
        RecoveryNonSubroNonSecondInjuryFundIndemnity,
        RecoveryNonSubroNonSecondInjuryFundLegal,
        RecoveryNonSubroNonSecondInjuryFundMedical,
        TransactionAmount,
        RecoveryDeductibleEmployerLiability,
        RecoveryDeductibleExpense,
        RecoveryDeductibleIndemnity,
        RecoveryDeductibleMedical,
        RecoveryDeductibleLegal,
        HashValue,
        RetiredInd,
        AuditOperations,
        LoadUpdateDate,
        LoadCreateDate
    FROM Semantic.ClaimTransactionMeasures
    WHERE LoadUpdateDate >= @pJobStartDateTime;
END;

-- Note: In Microsoft Fabric, indexes are managed automatically
-- No need to manually rebuild indexes as in the original SQL Server procedure